### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by hayribakici** [BoD/android-activitylifecyclecallbacks-compat#4]
Hi,
is it possible to make this library a maven project?

cheers

**Comment by BoD** [comment]
To be honest, I will probably never do this, as the new recommended way to do this is to use Gradle.
Unfortunately I still never had the chance to look at Gradle, so I can't make the Gradle config just yet either - but I will definitely do it some day :)

**Comment by BoD** [comment]
Following this in issue #5
